#!/bin/sh
### BEGIN INIT INFO
# Provides:          amiproxy
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AMI proxy between xivo-ctid and asterisk
### END INIT INFO

PATH=/usr/sbin:/usr/bin:/sbin:/bin

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting" "amiproxy"
    if amiproxy --background;
    then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping" "amiproxy"
    pkill amiproxy
    log_end_msg 1
    ;;
  reload|restart|force-reload)
    ;;
  *)
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
