#!/usr/bin/env python2

# -*- coding: utf-8 -*-
# Copyright 2017 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0+

import os
import subprocess
import sys


def main():
    files = list_files_to_commit()

    if 'debian/changelog' not in files:
        print "Please update the changelog before committing."
        sys.exit(1)


def list_files_to_commit():
    cmd = ['git', 'diff', '--cached', '--name-only', '--diff-filter=MA']
    output = subprocess.check_output(cmd).strip()
    if not output:
        return []
    return [l.strip() for l in output.split("\n") if not os.path.islink(l.strip())]


if __name__ == "__main__":
    main()
