#!/bin/sh

export PATH=$PATH:/usr/sbin

IFACE_DATA="eth0"
IP_VIP_DATA="192.168.51.162"
IP_LOCAL_XV_DATA="192.168.51.160"
NETMASK_DATA_LENGTH="24"
NETWORK_DATA="192.168.51.0"

IFACE_VOIP="eth0.590"
IP_VIP_VOIP="10.59.0.10"
IP_LOCAL_XV_VOIP="10.59.0.1"
NETMASK_VOIP_LENGTH="24"
NETWORK_VOIP="10.59.0.0"

usage() {
    cat << EOF
    Script which sets the Virtual IP for each interface
    usage: $(basename $0) action
        action: start or stop to enable/disable Virtual IPs
EOF
}

enable_virtual_ip() {

	# VLAN Data
	ip addr add ${IP_VIP_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA}
	ip ro change ${NETWORK_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA} src ${IP_VIP_DATA}
	arping -S ${IP_VIP_DATA} -c 5 -i ${IFACE_DATA} -B

	# VLAN VoIP
	ip addr add ${IP_VIP_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP}
	ip ro change ${NETWORK_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP} src ${IP_VIP_VOIP}
	arping -S ${IP_VIP_VOIP} -c 5 -i ${IFACE_VOIP} -B
}


disable_virtual_ip() {

	# VLAN Data
	ip ro change ${NETWORK_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA} src ${IP_LOCAL_XV_DATA}
	ip addr del ${IP_VIP_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA}
	arping -S ${IP_LOCAL_XV_DATA} -c 5 -i ${IFACE_DATA} -B

	# VLAN VoIP
	ip ro change ${NETWORK_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP} src ${IP_LOCAL_XV_VOIP}
	ip addr del ${IP_VIP_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP}
	arping -S ${IP_LOCAL_XV_VOIP} -c 5 -i ${IFACE_VOIP} -B
}

case $1 in
    start) enable_virtual_ip;;
    stop)  disable_virtual_ip;;
    *) usage;;
esac

