#!/usr/bin/env python2

# -*- coding: utf-8 -*-
# Copyright 2016 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0+

import os
import re
import stat
import subprocess
import sys

from datetime import datetime

COPYRIGHT_TPL = "{}Copyright (C) {}-{} The Wazo Authors  (see the AUTHORS file)"


def main():
    abort = False
    for filepath in find_files_to_check():
        copyright = find_copyright(filepath)
        if copyright is None:
            print "WARNING: {} has no copyright".format(filepath)
        elif copyright and not copyright_ok(copyright):
            fix_copyright(filepath, copyright)
            abort = True

    if abort:
        print "Files have been changed. Please add and commit again."
        sys.exit(1)


def find_files_to_check():
    cmd = ['git', 'diff', '--cached', '--name-only', '--diff-filter=MA']
    output = subprocess.check_output(cmd).strip()
    if not output:
        return []
    return [l.strip() for l in output.split("\n") if not is_symlink(l.strip())]


def is_symlink(path):
    path_stat = os.lstat(path)
    return stat.S_ISLNK(path_stat.st_mode)


def find_copyright(filepath):
    year = datetime.now().year
    with open(filepath) as f:
        for line in f:
            match = re.search(r"(.*)copyright.*?(\d+).*".format(year), line, re.IGNORECASE)
            if match:
                return match
    return None


def copyright_ok(match):
    current_year = str(datetime.now().year)
    return current_year in match.group(0)


def fix_copyright(filepath, match):
    prefix = match.group(1)
    first_year = match.group(2)
    current_year = datetime.now().year
    new_copyright = COPYRIGHT_TPL.format(prefix, first_year, current_year)
    change_copyright(filepath, match.group(0), new_copyright)


def change_copyright(filepath, old, new):
    print '{}: "{}" -> "{}"'.format(filepath, old, new)
    with open(filepath) as f:
        text = f.read()
    with open(filepath, 'w') as f:
        text = text.replace(old, new)
        f.write(text)


if __name__ == "__main__":
    main()
