#!/usr/bin/env python
import argparse

from fabric.api import run
from fabric.decorators import hosts
from fabric.tasks import execute

XIVO_TEST_HOST = "root@xivo-test"
XIVO_TEST_SLAVE_HOST = "root@xivo-test-slave"
FARM_HOST = "root@wheezy-farm.xivo.io"
MIRROR_HOST = "root@mirror.xivo.io"


def freeze():
    execute(check_server_started)
    execute(check_slave_started)
    execute(backup_server)
    execute(build_packages)
    execute(synchronize_mirrors)
    execute(clear_confgen_cache)
    execute(upgrade_xivo_test)

    print
    print "RC is ready !"
    print


@hosts(XIVO_TEST_HOST)
def check_server_started():
    run('ls')


@hosts(XIVO_TEST_SLAVE_HOST)
def check_slave_started():
    run('ls')


@hosts(XIVO_TEST_HOST)
def backup_server():
    run('xivo-service stop')
    run('xivo-backup data /var/backups/xivo/data')
    run('xivo-backup db /var/backups/xivo/db')
    run('xivo-service start')


@hosts(FARM_HOST)
def build_packages():
    run('packaging-farm --cd skaro rebuild')


@hosts(XIVO_TEST_HOST)
def clear_confgen_cache():
    run('rm -f /var/lib/xivo-confgend/asterisk/*')


@hosts(MIRROR_HOST)
def synchronize_mirrors():
    run('./update_xivo-dev')
    run('./update_xivo-rc')


@hosts(XIVO_TEST_HOST)
def upgrade_xivo_test():
    run('xivo-upgrade -f')


if __name__ == "__main__":
    freeze()
