#!/usr/bin/env python
# Copyright (C) 2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from fabric.api import run
from fabric.decorators import hosts
from fabric.tasks import execute

XIVO_TEST_HOST = "root@xivo-test"
XIVO_TEST_SLAVE_HOST = "root@xivo-test-slave"
FARM_HOST = "root@wheezy-farm.xivo.io"
MIRROR_HOST = "root@mirror.xivo.io"


def freeze():
    execute(check_server_started)
    execute(check_slave_started)
    execute(backup_server)
    execute(synchronize_mirrors)
    execute(clear_confgen_cache)
    execute(upgrade_xivo_test)
    execute(upgrade_xivo_test_slave)

    print
    print "RC is ready !"
    print


@hosts(XIVO_TEST_HOST)
def check_server_started():
    run('ls')


@hosts(XIVO_TEST_SLAVE_HOST)
def check_slave_started():
    run('ls')


@hosts(XIVO_TEST_HOST)
def backup_server():
    run('xivo-service stop')
    run('xivo-backup data /var/backups/xivo/data')
    run('xivo-backup db /var/backups/xivo/db')
    run('xivo-service start')
    run('xivo-backup-consul-kv -o /var/backups/xivo/consul-kv.json')


@hosts(XIVO_TEST_HOST)
def clear_confgen_cache():
    run('rm -f /var/lib/xivo-confgend/asterisk/*')


@hosts(MIRROR_HOST)
def synchronize_mirrors():
    run('reprepro -vb /data/reprepro/xivo update xivo-rc')


@hosts(XIVO_TEST_HOST)
def upgrade_xivo_test():
    run('xivo-upgrade -f')


@hosts(XIVO_TEST_SLAVE_HOST)
def upgrade_xivo_test_slave():
    run('xivo-upgrade -f')


if __name__ == "__main__":
    freeze()
