# -*- coding: UTF-8 -*-

# Entity
# ======

ENTITY_NAME = 'avencall' # read when creating contexts

# Context
# =======

INTERNAL_CONTEXT_USER_START = 7000
INTERNAL_CONTEXT_USER_END = 9999
INTERNAL_CONTEXT_QUEUE_START = 3000
INTERNAL_CONTEXT_QUEUE_END = 3099

# Users
# =====

NB_USERS = 1800
USER_START_NUMBER = INTERNAL_CONTEXT_USER_START

# Agents
# ======

NB_AGENTS = 200
AGENT_START_NUMBER = 9000

# Queues
# ======

NB_QUEUES = 10
QUEUE_START_NUMBER = INTERNAL_CONTEXT_QUEUE_START

# Conference rooms
# ================

NB_CONFROOMS = 100
CONFROOMS_START_NUMBER = 2000
