#!/usr/bin/env python
import argparse

from fabric.api import run
from fabric.decorators import hosts
from fabric.tasks import execute

KVM_HOST = "root@kvm-2-dev"
XIVO_TEST_HOST = "root@xivo-test"
XIVO_TEST_SLAVE_HOST = "root@xivo-test-slave"
FARM_HOST = "root@wheezy-farm.xivo.fr"
MIRROR_HOST = "root@mirror.xivo.fr"


def freeze(previous, release):
    execute(check_server_started)
    execute(check_slave_started)
    execute(backup_server)
    execute(build_packages)
    execute(synchronize_mirrors)
    execute(clear_confgen_cache)
    execute(upgrade_xivo_test)

    print
    print "RC is ready !"
    print


@hosts(XIVO_TEST_HOST)
def check_server_started():
    run('ls')


@hosts(XIVO_TEST_SLAVE_HOST)
def check_slave_started():
    run('ls')


@hosts(XIVO_TEST_HOST)
def backup_server():
    run('xivo-backup data /var/backups/xivo/data')
    run('xivo-backup db /var/backups/xivo/db')


@hosts(FARM_HOST)
def build_packages():
    run('packaging-farm --cd skaro rebuild')


@hosts(XIVO_TEST_HOST)
def clear_confgen_cache():
    run('rm -f /var/lib/xivo-confgend/asterisk/*')


@hosts(MIRROR_HOST)
def synchronize_mirrors():
    run('./update_xivo-rc')


@hosts(XIVO_TEST_HOST)
def upgrade_xivo_test():
    run('xivo-upgrade -f')


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('previous_version', help='previous XiVO version')
    parser.add_argument('rc_version', help='Version to freeze')

    args = parser.parse_args()
    freeze(args.previous_version, args.rc_version)
