#!/usr/bin/env python
import requests
import json
import click

from xivo_provd_client import new_provisioning_client

from IPython import embed


HOST = "dev"
PORT = 8666

HEADER = """A provd client is available as the 'p' variable.
You can interact with the client in the following ways:

devices.find()
configs.find()
"""


@click.command()
@click.option('--host', default=HOST)
@click.option('--port', default=PORT, type=click.INT)
def console(host, port):
    client = new_provisioning_client('http://{}:{}/provd'.format(host, port))
    devices = client.device_manager()
    configs= client.config_manager()
    embed(header=HEADER, user_ns={'client': client, 'devices': devices, 'configs': configs})


if __name__ == "__main__":
    console()
