#!/bin/bash -e

URL_REPOS_LIST="http://mirror.wazo.community/repos/shortlog"
GIT_DIRECTORIES=$(wget -qO - "$URL_REPOS_LIST")
if [ $? -ne 0 ]; then
    echo "Unable to fetch repositories list from $URL_REPOS_LIST."
    exit 1
fi

WAZO_CLIENT_DIRECTORY="wazo-client-qt"

version="$1"

if [ -z "$version" ]; then
    echo "usage: $(basename $0) <version>"
    exit 1
fi

print_header() {
    repository="$1"

    echo "======================================"
    echo "$repository"
    echo
}

print_shortlog() {
    tag_name="$1"

    if [ "$(git describe origin/master)" = "$tag_name" ]; then
	echo "No modification"
	echo
    else
	git --no-pager shortlog "$tag_name..origin/master"

	# XXX diff shows too much output
	#git --no-pager diff "$tag_name" origin/master
    fi
}

# normal repositories
tag_name="wazo-$version"

for git_directory in $GIT_DIRECTORIES; do
    cd "$git_directory" > /dev/null

    print_header "$git_directory"
    git fetch -q

    if [ -z "$(git tag -l "$tag_name")" ]; then
	echo "Error: this repository has no tag $tag_name"
	echo
    else
	print_shortlog "$tag_name"
    fi

    cd "$OLDPWD"
done

# wazo client repository
cd "$WAZO_CLIENT_DIRECTORY" > /dev/null

print_header "$WAZO_CLIENT_DIRECTORY"
git fetch -q

tag_name_prefix="wazo-client-$version"
tag_name=$(git tag -l "$tag_name_prefix*" | sort | tail -n1)
if [ -z "$tag_name" ]; then
    echo "Error: this repository has no tag $tag_name_prefix"
    echo
else
    if [ "$tag_name_prefix" != "$tag_name" ]; then
	echo "Using tag $tag_name instead of $tag_name_prefix"
	echo
    fi

    print_shortlog "$tag_name"
fi

cd "$OLDPWD"
