#!/bin/bash -e

current_jenkins_version=$(ssh root@jenkins dpkg-query -W -f='\${Version}' jenkins)
[[ $current_jenkins_version =~ ^[0-9]+\.[0-9]+$ ]]
echo "Current Jenkins version is $current_jenkins_version"

echo "Shutting down jenkins..."
ssh root@kvm-2-dev virsh shutdown jenkins.xivo.io
while [ "$(ssh kvm-2-dev virsh dominfo jenkins.xivo.io | grep State | awk '{print $2}')" = 'running' ] ; do
	sleep 5
done
echo "Snapshotting jenkins..."
ssh root@kvm-2-dev virsh snapshot-create-as jenkins.xivo.io "$current_jenkins_version"
ssh root@kvm-2-dev virsh start jenkins.xivo.io

echo "Waiting for jenkins to come back up..."
while ! ssh root@jenkins echo
do
	sleep 10
done

echo "Upgrading jenkins..."
ssh root@jenkins apt-get update
ssh root@jenkins DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
ssh root@jenkins DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
ssh root@jenkins apt-get -y autoremove

echo
echo "Things left to do:"
echo "1. (optional) reboot Jenkins: ssh root@jenkins reboot"
echo "2. delete oldest snapshot: ssh root@kvm-2-dev virsh snapshot-delete jenkins.xivo.io <snapshot>"
ssh root@kvm-2-dev virsh snapshot-list jenkins.xivo.io
echo "3. update Jenkins plugins"
