#!/bin/sh

. /etc/pf-xivo/virtual-ip-config.sh

remove_vip_from_iface() {
	VIP=$1
	IFACE=$2
	ip addr show dev ${IFACE} | grep ${VIP} > /dev/null
	if [ $? -eq 0 ]; then
		ip addr del ${VIP} dev ${IFACE}	
	fi
}

remove_vip_from_iface $VIP_DATA/$NETMASK_DATA_LENGTH $IFACE_DATA
remove_vip_from_iface $VIP_VOIP/$NETMASK_VOIP_LENGTH $IFACE_VOIP
/usr/local/sbin/synchronize-astdb from_slave
/etc/init.d/asterisk restart > /dev/null
exit 0
