#!/usr/bin/env python3

import argparse
import io
import logging
import os
import sh
import sqlalchemy as sa
import sqlalchemy_utils
import sys
import xivo_dao.alchemy.all

from configparser import ConfigParser

from alembic.config import Config as AlembicConfig
from alembic import command as alembic_command

from xivo_dao.helpers import db_manager

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('sh.stream_bufferer').setLevel(logging.WARNING)
logger = logging.getLogger('sh.streamreader').setLevel(logging.WARNING)
logger = logging.getLogger('sh.command').setLevel(logging.WARNING)

CWD_PATH = os.path.abspath(os.path.dirname(__file__))
DB_URI = "postgres://{username}:{password}@{host}/{dbname}"

config = ConfigParser()
config.read(os.path.join(CWD_PATH, 'defaults.ini'))


def argparser():
    parser = argparse.ArgumentParser('Compare Wazo database schemas and check for inconsistencies')
    parser.add_argument('--config', help='config file')
    return parser


def main():
    parser = argparser()
    args = parser.parse_args()

    if args.config:
        config.read(args.config)

    installed_postgresql_uri = config.get('database_uri', 'installed')
    migrated_postgresql_uri = config.get('database_uri', 'migrated')

    generate_installed_database(installed_postgresql_uri)
    generate_migrated_database(migrated_postgresql_uri)

    differences = compare_schemas(migrated_postgresql_uri, installed_postgresql_uri)

    if differences:
        print()
        print("These commands are showing what migration script should be added in order to obtain the same schema as a fresh install.")
        print("Differences detected from migrated to installed schema: ")
        print()
        print(differences)
        sys.exit(1)


def generate_installed_database(postgresql_uri):
    alembic_cfg = build_alembic_config(postgresql_uri)

    reset_database(postgresql_uri)
    create_tables(postgresql_uri)
    populate_db(postgresql_uri)
    # make sure stamp doesn't show up in diff
    alembic_command.stamp(alembic_cfg, 'head')


def generate_migrated_database(postgresql_uri):
    script = os.path.join(CWD_PATH, 'asterisk_migration.sql')

    reset_database(postgresql_uri)
    run_script(script, postgresql_uri)
    run_alembic_migrations(postgresql_uri)


def reset_database(postgresql_uri):
    drop_database(postgresql_uri)
    create_database(postgresql_uri)
    enable_extensions(postgresql_uri)


def drop_database(postgresql_uri):
    logging.info("dropping database")
    if sqlalchemy_utils.functions.database_exists(postgresql_uri):
        engine = sa.create_engine(postgresql_uri)
        engine.execute('DROP OWNED BY asterisk CASCADE;')
        engine.execute('DROP ROLE IF EXISTS asterisk;')
        engine.dispose()

        sqlalchemy_utils.functions.drop_database(postgresql_uri)


def create_database(postgresql_uri):
    logging.info("creating database")

    sqlalchemy_utils.functions.create_database(postgresql_uri)

    engine = sa.create_engine(postgresql_uri)
    engine.execute('CREATE ROLE asterisk WITH PASSWORD \'superpass\';')
    engine.dispose()


def enable_extensions(postgresql_uri):
    logging.info("enabling DB extensions")
    engine = sa.create_engine(postgresql_uri)
    engine.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    engine.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    engine.dispose()


def create_tables(postgresql_uri):
    logging.info("creating tables")

    engine = sa.create_engine(postgresql_uri)
    db_manager.Base.metadata.create_all(bind=engine)
    engine.dispose()


def populate_db(postgresql_uri):
    path = "{}/populate/populate.sql".format(config.get('repos', 'manage_db'))
    run_script(path, postgresql_uri)


def run_alembic_migrations(postgresql_uri):
    logging.info("running alembic migrations")
    alembic_cfg = build_alembic_config(postgresql_uri)
    os.environ['XIVO_UUID'] = '99999999-9999-9999-9999-999999999999'
    alembic_command.stamp(alembic_cfg, 'base')
    alembic_command.upgrade(alembic_cfg, 'head')


def build_alembic_config(postgresql_uri):
    alembic_path = "{}/alembic".format(config.get('repos', 'manage_db'))
    ini_file = "{}/alembic.ini".format(config.get('repos', 'manage_db'))

    alembic_cfg = AlembicConfig(ini_file)
    alembic_cfg.set_main_option("script_location", alembic_path)
    alembic_cfg.set_main_option("sqlalchemy.url", postgresql_uri)
    return alembic_cfg


def run_script(filepath, postgresql_uri):
    logging.info("running script %s", filepath)

    error_buffer = io.StringIO()

    sh.psql(
        '-qX',
        d=postgresql_uri,
        f=filepath,
        _err=error_buffer,
        _env={'PGOPTIONS': '--client-min-messages=warning'},  # prevents NOTICE:
    )

    errors = error_buffer.getvalue()
    if errors:
        logging.warn("errors while executing %s: %s", filepath, errors)
        sys.exit(2)


def compare_schemas(migrated_postgresql_uri, installed_postgresql_uri):
    # Return code 0 = no differences found
    # Return code 2 = found differences
    output = sh.migra(
        '--unsafe',
        migrated_postgresql_uri,
        installed_postgresql_uri,
        _ok_code=[0, 2],
    )
    return output


if __name__ == "__main__":
    main()
