#!/bin/sh
VIRTUAL_IP=$1
ping -c 1 $VIRTUAL_IP
if [ $? -eq 0 ]; then
	echo "Virtual IP is still active, no need to activate it now"
else
	echo "Mounting virtual IP on the master"
	/usr/local/sbin/ac-ha-manage-virtual-ip start
fi
