#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          relay-slave
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script mounting the Virtual IP once the slave has released it
### END INIT INFO
#
/usr/local/sbin/ac-ha-manage-virtual-ip stop
ping -c 1 10.59.0.10
while [ $? -eq 0 ]
do
	echo "Virtual IP is still mounted on the slave"
	ping -c 1 10.59.0.10
done
/usr/local/sbin/ac-ha-manage-virtual-ip start

