#!/bin/sh
#
# See http://projects.wazo.community/issues/6213

usage() {
    echo "usage: $0 <start timestamp> [<end timestamp>]" >&2
    exit 1
}

if [ -z "$1" ]; then
    usage
fi

start_ts="'$1'"
if [ "$2" ]; then
    end_ts="'$2'"
else
    end_ts="'$(date '+%F %T')'"
fi

echo 'Updating queue_log table...'
sudo -u postgres psql -v ON_ERROR_STOP= asterisk <<EOF
UPDATE
    queue_log
SET
    data2 = cast(data2 as int) + extract(epoch from (cast(time as timestamp) at time zone 'localtime' - cast(time as timestamp) at time zone 'GMT'))
WHERE
    event = 'AGENTCALLBACKLOGOFF'
    and time between $start_ts and $end_ts;
EOF

if [ $? -eq 0 ]; then
    echo 'Running "xivo-stat clean_db"'
    xivo-stat clean_db
    echo 'Running "xivo-stat fill_db" -- this might take a while'
    xivo-stat fill_db
fi
