#!/bin/sh
. /etc/pf-xivo/virtual-ip-config.sh
export PATH=$PATH:/usr/sbin

usage() {
    cat << EOF
    Script which sets the Virtual IP for each interface
    usage: $(basename $0) action
        action: start or stop to enable/disable Virtual IPs
EOF
}

enable_virtual_ip() {

	# VLAN Data
	ip addr add ${VIP_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA}
	ip ro change ${NETWORK_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA} src ${VIP_DATA}
	arping -S ${VIP_DATA} -c 5 -i ${IFACE_DATA} -B

	# VLAN VoIP
	ip addr add ${VIP_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP}
	ip ro change ${NETWORK_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP} src ${VIP_VOIP}
	arping -S ${VIP_VOIP} -c 5 -i ${IFACE_VOIP} -B
}


disable_virtual_ip() {

	# VLAN Data
	ip ro change ${NETWORK_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA} src ${LOCAL_IP_DATA}
	ip addr del ${VIP_DATA}/${NETMASK_DATA_LENGTH} dev ${IFACE_DATA}
	arping -S ${LOCAL_IP_DATA} -c 5 -i ${IFACE_DATA} -B

	# VLAN VoIP
	ip ro change ${NETWORK_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP} src ${LOCAL_IP_VOIP}
	ip addr del ${VIP_VOIP}/${NETMASK_VOIP_LENGTH} dev ${IFACE_VOIP}
	arping -S ${LOCAL_IP_VOIP} -c 5 -i ${IFACE_VOIP} -B
}

case $1 in
    start) enable_virtual_ip;;
    stop)  disable_virtual_ip;;
    *) usage;;
esac

