#!/bin/sh
. /etc/pf-xivo/virtual-ip-config.sh

ping -c 1 $VIP_VOIP
if [ $? -eq 0 ]; then
	echo "Virtual IP is still active, no need to activate it now"
else
	echo "Mounting virtual IP on the master"
	/usr/local/sbin/ac-ha-manage-virtual-ip start
fi
