#!/bin/bash

. /etc/pf-xivo/virtual-ip-config.sh

#FUNCTION
rsync_auto() {
        #VAR
        dest_ipbx=$1
        directory=$2
        special_arguments=${*:3}
        full_log="$LOG_DIRECTORY/daily-replicate-files.log"
        
        #SYNC
        rsync --links --archive --delete --perms --log-file="$full_log" "$directory" root@"$dest_ipbx":"$directory" $special_arguments
}


#SYNC
#sound files
rsync_auto "$PEER_IP_DATA" "/var/lib/asterisk/sounds/"
rsync_auto "$PEER_IP_DATA" "/var/lib/pf-xivo/sounds/"
#music on hold
rsync_auto "$PEER_IP_DATA" "/var/lib/asterisk/moh/"
#specific dialplan
rsync_auto "$PEER_IP_DATA" "/etc/asterisk/extensions_extra.d/"
#provisionning files
rsync_auto "$PEER_IP_DATA" "/var/lib/xivo-provd/"
#voicemails
rsync_auto "$PEER_IP_DATA" "/var/spool/asterisk/voicemail/"
