#!/bin/sh

. /etc/pf-xivo/virtual-ip-config.sh

LOG_FILE="$LOG_DIRECTORY/synchronize-astdb.log"

usage() {
  cat << EOF
  Script which replicates the astdb from or to the slave.
  usage: $(basename $0) action
    action: to_salve or from_slave
EOF
}

to_slave() {
  rsync --archive --perms --log-file="$LOG_FILE" /var/lib/asterisk/astdb.sqlite3 root@"$PEER_IP_DATA":/var/lib/asterisk/astdb.sqlite3
}

from_slave() {
  rsync -u --archive --perms --log-file="$LOG_FILE" root@"$PEER_IP_DATA":/var/lib/asterisk/astdb.sqlite3 /var/lib/asterisk/astdb.sqlite3
}

case $1 in
  to_slave) to_slave;;
  from_slave) from_slave;;
  *) usage;;
esac
