#!/bin/bash -e

cd /data/iso

candidates=$(find archives -maxdepth 1 -name '.xivo-*' -printf '%f\n')
if [ -z "$candidates" ]; then
    echo "Nothing to publish"
    exit 1
fi

for candidate in $candidates; do
    read -p "Do you want to publish ${candidate:1} [Y/n]? " answer
    if [ -z "$answer" -o "$answer" = 'y' -o '$answer' = "Y" ]; then
        mv "archives/$candidate" "archives/${candidate:1}"
        ln -s -f -n "archives/${candidate:1}" xivo-current
        echo "Published ${candidate:1}"
    fi
done
